name: buildflow
on: [push]

env:
  GO_VERSION: 1.18.1

jobs:
  unit-tests:
    name: unit-tests
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: make magic
        run: |
          make go-mod
          make unit-tests
  app-tests:
    name: app-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: make magic
        run: |
          make go-mod
          make build
          make app-tests
  go-build:
    name: build
    needs:
      - unit-tests
      - app-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: make magic
        run: |
          make build GIT_COMMIT=${{ github.sha }}