name: release
on:
  push:
    branches:
      - main
      - 'releases/**'
    tags:
      - v1.*

env:
  GO_VERSION: 1.18.1

jobs:

  go-build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: make magic
        run: |
          make build GIT_COMMIT=${{ github.sha }}
          make run-help
  go-release:
    name: release
    needs:
      - go-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: grandy
          path: dist/*